# Generated by Django 4.0.5 on 2022-06-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(choices=[('PY', 'job_python'), ('REACT', 'job_react'), ('JAVA', 'job_javadevs')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Группа специализации')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название технологии')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание вакансии')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавления вакансии')),
                ('salary', models.PositiveIntegerField(verbose_name='Заработная плата')),
                ('remote', models.BooleanField(default=True, verbose_name='Удаленная работа')),
                ('relocation', models.BooleanField(default=True, verbose_name='Релокация')),
                ('employment', models.CharField(choices=[('FULLDAY', 'Полный день'), ('NOTFULL', 'Неполный день'), ('PRJ', 'Проектная занятость'), ('PRTTIME', 'Частичная занятость')], max_length=7, verbose_name='Занятость')),
                ('skill', models.CharField(choices=[('IN', 'Intern'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('TL', 'TeamLead')], max_length=2, verbose_name='Уровень квалификации')),
                ('tasks', models.TextField(verbose_name='Задачи')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('contact', models.URLField(verbose_name='Ссылка на работодателя')),
                ('url', models.SlugField(verbose_name='Адрес вакансии')),
                ('message_id', models.IntegerField(verbose_name='ID cообщения в telegram-канале')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.channel')),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='vacancies.location', verbose_name='Локация')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.role')),
                ('technologies', models.ManyToManyField(related_name='technologies_required', to='vacancies.technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-add_date'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.rolegroup'),
        ),
    ]
