# Generated by Django 4.0.5 on 2022-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='telegram',
            field=models.TextField(default='RRR', null=True, verbose_name='Ссылка на телеграмм'),
        ),
    ]
