# Generated by Django 4.0.5 on 2022-06-11 23:03

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='max_salary',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=10, verbose_name='Максимальная заработная плата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_salary',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=10, verbose_name='Минимальная заработная плата'),
        ),
    ]
