# Generated by Django 4.0.5 on 2022-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_remove_vacancy_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='message_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID cообщения в telegram-канале'),
        ),
    ]
