# Generated by Django 4.0.5 on 2022-06-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancies_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='telegram',
            field=models.CharField(default='', max_length=20, verbose_name='Ссылка на телеграмм'),
        ),
    ]
