# Generated by Django 4.0.5 on 2022-06-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_message_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='rolegroup',
            options={'verbose_name': 'Группа специализации', 'verbose_name_plural': 'Группы специализации'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_salary',
            field=models.PositiveIntegerField(null=True, verbose_name='Максимальная заработная плата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='min_salary',
            field=models.PositiveIntegerField(null=True, verbose_name='Минимальная заработная плата'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название специализации'),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='message_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID cообщения в telegram-канале'),
        ),
    ]
