# Generated by Django 4.0.5 on 2022-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_max_salary_alter_vacancy_min_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['add_date'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(choices=[('Полный день', 'Полный день'), ('Неполный день', 'Неполный день'), ('Проектная занятость', 'Проектная занятость'), ('Частичная занятость', 'Частичная занятость'), ('Не указана', 'Не указана')], default='NONE', max_length=20, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skill',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('TeamLead', 'TeamLead'), ('Не указан', 'Не указан')], default='NONE', max_length=10, verbose_name='Уровень квалификации'),
        ),
    ]
