# Generated by Django 4.0.5 on 2022-07-01 19:15

from django.db import migrations, models
import django.db.models.deletion
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(default=vacancies.models.RoleGroup.get_default_group_id, on_delete=django.db.models.deletion.CASCADE, to='vacancies.rolegroup'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, default='Не указано', verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='tasks',
            field=models.TextField(blank=True, default='Не указано', verbose_name='Задачи'),
        ),
    ]
