# Generated by Django 4.0.5 on 2022-06-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_role_options_alter_rolegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.CharField(choices=[('PY', 'job_python'), ('REACT', 'job_react'), ('JAVA', 'job_javadevs')], max_length=10, verbose_name='Адрес Telegram-канала'),
        ),
    ]
