# Generated by Django 4.0.5 on 2022-06-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_location_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='vacancies.location'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='technologies',
            field=models.ManyToManyField(related_name='tech', to='vacancies.technologies'),
        ),
    ]
