# Generated by Django 4.0.5 on 2022-06-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_channel_options_alter_channel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.channel', verbose_name='Telegram-канал, откуда пришла вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.SlugField(verbose_name='Адрес для вакансии на сайте'),
        ),
    ]
