# Generated by Django 4.0.5 on 2022-06-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancies_location_vacancies_technologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='technologies',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
    ]
