# Generated by Django 4.0.5 on 2022-06-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancy_channel_id_alter_vacancy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.role', verbose_name='Специализация'),
        ),
    ]
