# Generated by Django 4.0.5 on 2022-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.CharField(choices=[('PY', 'job_python'), ('REACT', 'job_react'), ('JAVA', 'job_javadevs')], max_length=10, unique=True, verbose_name='Адрес Telegram-канала'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название специализации'),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название технологии'),
        ),
    ]
