# Generated by Django 4.0.5 on 2022-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_channel_url_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('country', 'city')},
        ),
    ]
