# Generated by Django 4.0.5 on 2022-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_alter_channel_url_alter_vacancy_employment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='contact',
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.CharField(max_length=50, unique=True, verbose_name='Адрес Telegram-канала'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.SlugField(default=models.TextField(verbose_name='Описание вакансии'), verbose_name='Адрес для вакансии на сайте'),
        ),
    ]
